//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIC_Monitoring.DHPO {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.eClaimLink.ae/", ConfigurationName="DHPO.ValidateTransactionsSoap")]
    public interface ValidateTransactionsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/GetNewTransactions", ReplyAction="*")]
        OIC_Monitoring.DHPO.GetNewTransactionsResponse GetNewTransactions(OIC_Monitoring.DHPO.GetNewTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/GetNewTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<OIC_Monitoring.DHPO.GetNewTransactionsResponse> GetNewTransactionsAsync(OIC_Monitoring.DHPO.GetNewTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/GetNewPriorAuthorizationTransactions", ReplyAction="*")]
        OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsResponse GetNewPriorAuthorizationTransactions(OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/GetNewPriorAuthorizationTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsResponse> GetNewPriorAuthorizationTransactionsAsync(OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/UploadTransaction", ReplyAction="*")]
        OIC_Monitoring.DHPO.UploadTransactionResponse UploadTransaction(OIC_Monitoring.DHPO.UploadTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/UploadTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<OIC_Monitoring.DHPO.UploadTransactionResponse> UploadTransactionAsync(OIC_Monitoring.DHPO.UploadTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/DownloadTransactionFile", ReplyAction="*")]
        OIC_Monitoring.DHPO.DownloadTransactionFileResponse DownloadTransactionFile(OIC_Monitoring.DHPO.DownloadTransactionFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/DownloadTransactionFile", ReplyAction="*")]
        System.Threading.Tasks.Task<OIC_Monitoring.DHPO.DownloadTransactionFileResponse> DownloadTransactionFileAsync(OIC_Monitoring.DHPO.DownloadTransactionFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/CheckForNewPriorAuthorizationTransactions", ReplyAction="*")]
        OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsResponse CheckForNewPriorAuthorizationTransactions(OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/CheckForNewPriorAuthorizationTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsResponse> CheckForNewPriorAuthorizationTransactionsAsync(OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/SetTransactionDownloaded", ReplyAction="*")]
        OIC_Monitoring.DHPO.SetTransactionDownloadedResponse SetTransactionDownloaded(OIC_Monitoring.DHPO.SetTransactionDownloadedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/SetTransactionDownloaded", ReplyAction="*")]
        System.Threading.Tasks.Task<OIC_Monitoring.DHPO.SetTransactionDownloadedResponse> SetTransactionDownloadedAsync(OIC_Monitoring.DHPO.SetTransactionDownloadedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/SearchTransactions", ReplyAction="*")]
        OIC_Monitoring.DHPO.SearchTransactionsResponse SearchTransactions(OIC_Monitoring.DHPO.SearchTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/SearchTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<OIC_Monitoring.DHPO.SearchTransactionsResponse> SearchTransactionsAsync(OIC_Monitoring.DHPO.SearchTransactionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewTransactions", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public OIC_Monitoring.DHPO.GetNewTransactionsRequestBody Body;
        
        public GetNewTransactionsRequest() {
        }
        
        public GetNewTransactionsRequest(OIC_Monitoring.DHPO.GetNewTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class GetNewTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public GetNewTransactionsRequestBody() {
        }
        
        public GetNewTransactionsRequestBody(string login, string pwd) {
            this.login = login;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewTransactionsResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public OIC_Monitoring.DHPO.GetNewTransactionsResponseBody Body;
        
        public GetNewTransactionsResponse() {
        }
        
        public GetNewTransactionsResponse(OIC_Monitoring.DHPO.GetNewTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class GetNewTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetNewTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlTransaction;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public GetNewTransactionsResponseBody() {
        }
        
        public GetNewTransactionsResponseBody(int GetNewTransactionsResult, string xmlTransaction, string errorMessage) {
            this.GetNewTransactionsResult = GetNewTransactionsResult;
            this.xmlTransaction = xmlTransaction;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewPriorAuthorizationTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewPriorAuthorizationTransactions", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsRequestBody Body;
        
        public GetNewPriorAuthorizationTransactionsRequest() {
        }
        
        public GetNewPriorAuthorizationTransactionsRequest(OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class GetNewPriorAuthorizationTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public GetNewPriorAuthorizationTransactionsRequestBody() {
        }
        
        public GetNewPriorAuthorizationTransactionsRequestBody(string login, string pwd) {
            this.login = login;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewPriorAuthorizationTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewPriorAuthorizationTransactionsResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsResponseBody Body;
        
        public GetNewPriorAuthorizationTransactionsResponse() {
        }
        
        public GetNewPriorAuthorizationTransactionsResponse(OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class GetNewPriorAuthorizationTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetNewPriorAuthorizationTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlTransaction;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public GetNewPriorAuthorizationTransactionsResponseBody() {
        }
        
        public GetNewPriorAuthorizationTransactionsResponseBody(int GetNewPriorAuthorizationTransactionsResult, string xmlTransaction, string errorMessage) {
            this.GetNewPriorAuthorizationTransactionsResult = GetNewPriorAuthorizationTransactionsResult;
            this.xmlTransaction = xmlTransaction;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadTransaction", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public OIC_Monitoring.DHPO.UploadTransactionRequestBody Body;
        
        public UploadTransactionRequest() {
        }
        
        public UploadTransactionRequest(OIC_Monitoring.DHPO.UploadTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class UploadTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] fileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fileName;
        
        public UploadTransactionRequestBody() {
        }
        
        public UploadTransactionRequestBody(string login, string pwd, byte[] fileContent, string fileName) {
            this.login = login;
            this.pwd = pwd;
            this.fileContent = fileContent;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadTransactionResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public OIC_Monitoring.DHPO.UploadTransactionResponseBody Body;
        
        public UploadTransactionResponse() {
        }
        
        public UploadTransactionResponse(OIC_Monitoring.DHPO.UploadTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class UploadTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UploadTransactionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] errorReport;
        
        public UploadTransactionResponseBody() {
        }
        
        public UploadTransactionResponseBody(int UploadTransactionResult, string errorMessage, byte[] errorReport) {
            this.UploadTransactionResult = UploadTransactionResult;
            this.errorMessage = errorMessage;
            this.errorReport = errorReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadTransactionFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadTransactionFile", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public OIC_Monitoring.DHPO.DownloadTransactionFileRequestBody Body;
        
        public DownloadTransactionFileRequest() {
        }
        
        public DownloadTransactionFileRequest(OIC_Monitoring.DHPO.DownloadTransactionFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class DownloadTransactionFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileId;
        
        public DownloadTransactionFileRequestBody() {
        }
        
        public DownloadTransactionFileRequestBody(string login, string pwd, string fileId) {
            this.login = login;
            this.pwd = pwd;
            this.fileId = fileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadTransactionFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadTransactionFileResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public OIC_Monitoring.DHPO.DownloadTransactionFileResponseBody Body;
        
        public DownloadTransactionFileResponse() {
        }
        
        public DownloadTransactionFileResponse(OIC_Monitoring.DHPO.DownloadTransactionFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class DownloadTransactionFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DownloadTransactionFileResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] file;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string errorMessage;
        
        public DownloadTransactionFileResponseBody() {
        }
        
        public DownloadTransactionFileResponseBody(int DownloadTransactionFileResult, string fileName, byte[] file, string errorMessage) {
            this.DownloadTransactionFileResult = DownloadTransactionFileResult;
            this.fileName = fileName;
            this.file = file;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckForNewPriorAuthorizationTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckForNewPriorAuthorizationTransactions", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsRequestBody Body;
        
        public CheckForNewPriorAuthorizationTransactionsRequest() {
        }
        
        public CheckForNewPriorAuthorizationTransactionsRequest(OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class CheckForNewPriorAuthorizationTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public CheckForNewPriorAuthorizationTransactionsRequestBody() {
        }
        
        public CheckForNewPriorAuthorizationTransactionsRequestBody(string login, string pwd) {
            this.login = login;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckForNewPriorAuthorizationTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckForNewPriorAuthorizationTransactionsResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsResponseBody Body;
        
        public CheckForNewPriorAuthorizationTransactionsResponse() {
        }
        
        public CheckForNewPriorAuthorizationTransactionsResponse(OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class CheckForNewPriorAuthorizationTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CheckForNewPriorAuthorizationTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMessage;
        
        public CheckForNewPriorAuthorizationTransactionsResponseBody() {
        }
        
        public CheckForNewPriorAuthorizationTransactionsResponseBody(int CheckForNewPriorAuthorizationTransactionsResult, string errorMessage) {
            this.CheckForNewPriorAuthorizationTransactionsResult = CheckForNewPriorAuthorizationTransactionsResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetTransactionDownloadedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetTransactionDownloaded", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public OIC_Monitoring.DHPO.SetTransactionDownloadedRequestBody Body;
        
        public SetTransactionDownloadedRequest() {
        }
        
        public SetTransactionDownloadedRequest(OIC_Monitoring.DHPO.SetTransactionDownloadedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class SetTransactionDownloadedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fieldId;
        
        public SetTransactionDownloadedRequestBody() {
        }
        
        public SetTransactionDownloadedRequestBody(string login, string pwd, string fieldId) {
            this.login = login;
            this.pwd = pwd;
            this.fieldId = fieldId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetTransactionDownloadedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetTransactionDownloadedResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public OIC_Monitoring.DHPO.SetTransactionDownloadedResponseBody Body;
        
        public SetTransactionDownloadedResponse() {
        }
        
        public SetTransactionDownloadedResponse(OIC_Monitoring.DHPO.SetTransactionDownloadedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class SetTransactionDownloadedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SetTransactionDownloadedResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMessage;
        
        public SetTransactionDownloadedResponseBody() {
        }
        
        public SetTransactionDownloadedResponseBody(int SetTransactionDownloadedResult, string errorMessage) {
            this.SetTransactionDownloadedResult = SetTransactionDownloadedResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchTransactions", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public OIC_Monitoring.DHPO.SearchTransactionsRequestBody Body;
        
        public SearchTransactionsRequest() {
        }
        
        public SearchTransactionsRequest(OIC_Monitoring.DHPO.SearchTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class SearchTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int direction;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string callerLicense;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ePartner;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int transactionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int TransactionStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string transactionFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string transactionFromDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string transactionToDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int minRecordCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int maxRecordCount;
        
        public SearchTransactionsRequestBody() {
        }
        
        public SearchTransactionsRequestBody(string login, string pwd, int direction, string callerLicense, string ePartner, int transactionID, int TransactionStatus, string transactionFileName, string transactionFromDate, string transactionToDate, int minRecordCount, int maxRecordCount) {
            this.login = login;
            this.pwd = pwd;
            this.direction = direction;
            this.callerLicense = callerLicense;
            this.ePartner = ePartner;
            this.transactionID = transactionID;
            this.TransactionStatus = TransactionStatus;
            this.transactionFileName = transactionFileName;
            this.transactionFromDate = transactionFromDate;
            this.transactionToDate = transactionToDate;
            this.minRecordCount = minRecordCount;
            this.maxRecordCount = maxRecordCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchTransactionsResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public OIC_Monitoring.DHPO.SearchTransactionsResponseBody Body;
        
        public SearchTransactionsResponse() {
        }
        
        public SearchTransactionsResponse(OIC_Monitoring.DHPO.SearchTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class SearchTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SearchTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string foundTransactions;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public SearchTransactionsResponseBody() {
        }
        
        public SearchTransactionsResponseBody(int SearchTransactionsResult, string foundTransactions, string errorMessage) {
            this.SearchTransactionsResult = SearchTransactionsResult;
            this.foundTransactions = foundTransactions;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidateTransactionsSoapChannel : OIC_Monitoring.DHPO.ValidateTransactionsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidateTransactionsSoapClient : System.ServiceModel.ClientBase<OIC_Monitoring.DHPO.ValidateTransactionsSoap>, OIC_Monitoring.DHPO.ValidateTransactionsSoap {
        
        public ValidateTransactionsSoapClient() {
        }
        
        public ValidateTransactionsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidateTransactionsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateTransactionsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateTransactionsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OIC_Monitoring.DHPO.GetNewTransactionsResponse OIC_Monitoring.DHPO.ValidateTransactionsSoap.GetNewTransactions(OIC_Monitoring.DHPO.GetNewTransactionsRequest request) {
            return base.Channel.GetNewTransactions(request);
        }
        
        public int GetNewTransactions(string login, string pwd, out string xmlTransaction, out string errorMessage) {
            OIC_Monitoring.DHPO.GetNewTransactionsRequest inValue = new OIC_Monitoring.DHPO.GetNewTransactionsRequest();
            inValue.Body = new OIC_Monitoring.DHPO.GetNewTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            OIC_Monitoring.DHPO.GetNewTransactionsResponse retVal = ((OIC_Monitoring.DHPO.ValidateTransactionsSoap)(this)).GetNewTransactions(inValue);
            xmlTransaction = retVal.Body.xmlTransaction;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.GetNewTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OIC_Monitoring.DHPO.GetNewTransactionsResponse> OIC_Monitoring.DHPO.ValidateTransactionsSoap.GetNewTransactionsAsync(OIC_Monitoring.DHPO.GetNewTransactionsRequest request) {
            return base.Channel.GetNewTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<OIC_Monitoring.DHPO.GetNewTransactionsResponse> GetNewTransactionsAsync(string login, string pwd) {
            OIC_Monitoring.DHPO.GetNewTransactionsRequest inValue = new OIC_Monitoring.DHPO.GetNewTransactionsRequest();
            inValue.Body = new OIC_Monitoring.DHPO.GetNewTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            return ((OIC_Monitoring.DHPO.ValidateTransactionsSoap)(this)).GetNewTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsResponse OIC_Monitoring.DHPO.ValidateTransactionsSoap.GetNewPriorAuthorizationTransactions(OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsRequest request) {
            return base.Channel.GetNewPriorAuthorizationTransactions(request);
        }
        
        public int GetNewPriorAuthorizationTransactions(string login, string pwd, out string xmlTransaction, out string errorMessage) {
            OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsRequest inValue = new OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsRequest();
            inValue.Body = new OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsResponse retVal = ((OIC_Monitoring.DHPO.ValidateTransactionsSoap)(this)).GetNewPriorAuthorizationTransactions(inValue);
            xmlTransaction = retVal.Body.xmlTransaction;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.GetNewPriorAuthorizationTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsResponse> OIC_Monitoring.DHPO.ValidateTransactionsSoap.GetNewPriorAuthorizationTransactionsAsync(OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsRequest request) {
            return base.Channel.GetNewPriorAuthorizationTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsResponse> GetNewPriorAuthorizationTransactionsAsync(string login, string pwd) {
            OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsRequest inValue = new OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsRequest();
            inValue.Body = new OIC_Monitoring.DHPO.GetNewPriorAuthorizationTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            return ((OIC_Monitoring.DHPO.ValidateTransactionsSoap)(this)).GetNewPriorAuthorizationTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OIC_Monitoring.DHPO.UploadTransactionResponse OIC_Monitoring.DHPO.ValidateTransactionsSoap.UploadTransaction(OIC_Monitoring.DHPO.UploadTransactionRequest request) {
            return base.Channel.UploadTransaction(request);
        }
        
        public int UploadTransaction(string login, string pwd, byte[] fileContent, string fileName, out string errorMessage, out byte[] errorReport) {
            OIC_Monitoring.DHPO.UploadTransactionRequest inValue = new OIC_Monitoring.DHPO.UploadTransactionRequest();
            inValue.Body = new OIC_Monitoring.DHPO.UploadTransactionRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileContent = fileContent;
            inValue.Body.fileName = fileName;
            OIC_Monitoring.DHPO.UploadTransactionResponse retVal = ((OIC_Monitoring.DHPO.ValidateTransactionsSoap)(this)).UploadTransaction(inValue);
            errorMessage = retVal.Body.errorMessage;
            errorReport = retVal.Body.errorReport;
            return retVal.Body.UploadTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OIC_Monitoring.DHPO.UploadTransactionResponse> OIC_Monitoring.DHPO.ValidateTransactionsSoap.UploadTransactionAsync(OIC_Monitoring.DHPO.UploadTransactionRequest request) {
            return base.Channel.UploadTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<OIC_Monitoring.DHPO.UploadTransactionResponse> UploadTransactionAsync(string login, string pwd, byte[] fileContent, string fileName) {
            OIC_Monitoring.DHPO.UploadTransactionRequest inValue = new OIC_Monitoring.DHPO.UploadTransactionRequest();
            inValue.Body = new OIC_Monitoring.DHPO.UploadTransactionRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileContent = fileContent;
            inValue.Body.fileName = fileName;
            return ((OIC_Monitoring.DHPO.ValidateTransactionsSoap)(this)).UploadTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OIC_Monitoring.DHPO.DownloadTransactionFileResponse OIC_Monitoring.DHPO.ValidateTransactionsSoap.DownloadTransactionFile(OIC_Monitoring.DHPO.DownloadTransactionFileRequest request) {
            return base.Channel.DownloadTransactionFile(request);
        }
        
        public int DownloadTransactionFile(string login, string pwd, string fileId, out string fileName, out byte[] file, out string errorMessage) {
            OIC_Monitoring.DHPO.DownloadTransactionFileRequest inValue = new OIC_Monitoring.DHPO.DownloadTransactionFileRequest();
            inValue.Body = new OIC_Monitoring.DHPO.DownloadTransactionFileRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileId = fileId;
            OIC_Monitoring.DHPO.DownloadTransactionFileResponse retVal = ((OIC_Monitoring.DHPO.ValidateTransactionsSoap)(this)).DownloadTransactionFile(inValue);
            fileName = retVal.Body.fileName;
            file = retVal.Body.file;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.DownloadTransactionFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OIC_Monitoring.DHPO.DownloadTransactionFileResponse> OIC_Monitoring.DHPO.ValidateTransactionsSoap.DownloadTransactionFileAsync(OIC_Monitoring.DHPO.DownloadTransactionFileRequest request) {
            return base.Channel.DownloadTransactionFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<OIC_Monitoring.DHPO.DownloadTransactionFileResponse> DownloadTransactionFileAsync(string login, string pwd, string fileId) {
            OIC_Monitoring.DHPO.DownloadTransactionFileRequest inValue = new OIC_Monitoring.DHPO.DownloadTransactionFileRequest();
            inValue.Body = new OIC_Monitoring.DHPO.DownloadTransactionFileRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileId = fileId;
            return ((OIC_Monitoring.DHPO.ValidateTransactionsSoap)(this)).DownloadTransactionFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsResponse OIC_Monitoring.DHPO.ValidateTransactionsSoap.CheckForNewPriorAuthorizationTransactions(OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsRequest request) {
            return base.Channel.CheckForNewPriorAuthorizationTransactions(request);
        }
        
        public int CheckForNewPriorAuthorizationTransactions(string login, string pwd, out string errorMessage) {
            OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsRequest inValue = new OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsRequest();
            inValue.Body = new OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsResponse retVal = ((OIC_Monitoring.DHPO.ValidateTransactionsSoap)(this)).CheckForNewPriorAuthorizationTransactions(inValue);
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.CheckForNewPriorAuthorizationTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsResponse> OIC_Monitoring.DHPO.ValidateTransactionsSoap.CheckForNewPriorAuthorizationTransactionsAsync(OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsRequest request) {
            return base.Channel.CheckForNewPriorAuthorizationTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsResponse> CheckForNewPriorAuthorizationTransactionsAsync(string login, string pwd) {
            OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsRequest inValue = new OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsRequest();
            inValue.Body = new OIC_Monitoring.DHPO.CheckForNewPriorAuthorizationTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            return ((OIC_Monitoring.DHPO.ValidateTransactionsSoap)(this)).CheckForNewPriorAuthorizationTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OIC_Monitoring.DHPO.SetTransactionDownloadedResponse OIC_Monitoring.DHPO.ValidateTransactionsSoap.SetTransactionDownloaded(OIC_Monitoring.DHPO.SetTransactionDownloadedRequest request) {
            return base.Channel.SetTransactionDownloaded(request);
        }
        
        public int SetTransactionDownloaded(string login, string pwd, string fieldId, out string errorMessage) {
            OIC_Monitoring.DHPO.SetTransactionDownloadedRequest inValue = new OIC_Monitoring.DHPO.SetTransactionDownloadedRequest();
            inValue.Body = new OIC_Monitoring.DHPO.SetTransactionDownloadedRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fieldId = fieldId;
            OIC_Monitoring.DHPO.SetTransactionDownloadedResponse retVal = ((OIC_Monitoring.DHPO.ValidateTransactionsSoap)(this)).SetTransactionDownloaded(inValue);
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.SetTransactionDownloadedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OIC_Monitoring.DHPO.SetTransactionDownloadedResponse> OIC_Monitoring.DHPO.ValidateTransactionsSoap.SetTransactionDownloadedAsync(OIC_Monitoring.DHPO.SetTransactionDownloadedRequest request) {
            return base.Channel.SetTransactionDownloadedAsync(request);
        }
        
        public System.Threading.Tasks.Task<OIC_Monitoring.DHPO.SetTransactionDownloadedResponse> SetTransactionDownloadedAsync(string login, string pwd, string fieldId) {
            OIC_Monitoring.DHPO.SetTransactionDownloadedRequest inValue = new OIC_Monitoring.DHPO.SetTransactionDownloadedRequest();
            inValue.Body = new OIC_Monitoring.DHPO.SetTransactionDownloadedRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fieldId = fieldId;
            return ((OIC_Monitoring.DHPO.ValidateTransactionsSoap)(this)).SetTransactionDownloadedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OIC_Monitoring.DHPO.SearchTransactionsResponse OIC_Monitoring.DHPO.ValidateTransactionsSoap.SearchTransactions(OIC_Monitoring.DHPO.SearchTransactionsRequest request) {
            return base.Channel.SearchTransactions(request);
        }
        
        public int SearchTransactions(string login, string pwd, int direction, string callerLicense, string ePartner, int transactionID, int TransactionStatus, string transactionFileName, string transactionFromDate, string transactionToDate, int minRecordCount, int maxRecordCount, out string foundTransactions, out string errorMessage) {
            OIC_Monitoring.DHPO.SearchTransactionsRequest inValue = new OIC_Monitoring.DHPO.SearchTransactionsRequest();
            inValue.Body = new OIC_Monitoring.DHPO.SearchTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.direction = direction;
            inValue.Body.callerLicense = callerLicense;
            inValue.Body.ePartner = ePartner;
            inValue.Body.transactionID = transactionID;
            inValue.Body.TransactionStatus = TransactionStatus;
            inValue.Body.transactionFileName = transactionFileName;
            inValue.Body.transactionFromDate = transactionFromDate;
            inValue.Body.transactionToDate = transactionToDate;
            inValue.Body.minRecordCount = minRecordCount;
            inValue.Body.maxRecordCount = maxRecordCount;
            OIC_Monitoring.DHPO.SearchTransactionsResponse retVal = ((OIC_Monitoring.DHPO.ValidateTransactionsSoap)(this)).SearchTransactions(inValue);
            foundTransactions = retVal.Body.foundTransactions;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.SearchTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OIC_Monitoring.DHPO.SearchTransactionsResponse> OIC_Monitoring.DHPO.ValidateTransactionsSoap.SearchTransactionsAsync(OIC_Monitoring.DHPO.SearchTransactionsRequest request) {
            return base.Channel.SearchTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<OIC_Monitoring.DHPO.SearchTransactionsResponse> SearchTransactionsAsync(string login, string pwd, int direction, string callerLicense, string ePartner, int transactionID, int TransactionStatus, string transactionFileName, string transactionFromDate, string transactionToDate, int minRecordCount, int maxRecordCount) {
            OIC_Monitoring.DHPO.SearchTransactionsRequest inValue = new OIC_Monitoring.DHPO.SearchTransactionsRequest();
            inValue.Body = new OIC_Monitoring.DHPO.SearchTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.direction = direction;
            inValue.Body.callerLicense = callerLicense;
            inValue.Body.ePartner = ePartner;
            inValue.Body.transactionID = transactionID;
            inValue.Body.TransactionStatus = TransactionStatus;
            inValue.Body.transactionFileName = transactionFileName;
            inValue.Body.transactionFromDate = transactionFromDate;
            inValue.Body.transactionToDate = transactionToDate;
            inValue.Body.minRecordCount = minRecordCount;
            inValue.Body.maxRecordCount = maxRecordCount;
            return ((OIC_Monitoring.DHPO.ValidateTransactionsSoap)(this)).SearchTransactionsAsync(inValue);
        }
    }
}
